services:
  postgres:
    image: postgres:16
    container_name: b2b_postgres
    restart: unless-stopped
    
    # Con esto basta. Docker inyectará todo tu .env automáticamente.
    env_file:
      - ../.env
      
    ports:
      - "5432:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: b2b_streamlit
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  postgres_data: